version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kaytros
      - MONGO_INITDB_ROOT_PASSWORD=letmein
    volumes:
      - mymongo-data: /data/db
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=kaytros
      - ME_CONFIG_MONGODB_ADMINPASSWORD=letmein
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mymongo-data:
    driver: local